config/routes.rb
Smartorhot::Application.routes.draw do
  resources :extended_profiles
  match 'vote_smart/:id' => 'extended_profiles#vote_smart'
  match 'vote_dumb/:id' => 'extended_profiles#vote_dumb'
  match 'vote_hot/:id' => 'extended_profiles#vote_hot'
  match 'vote_ugly/:id' => 'extended_profiles#vote_ugly'
  
  devise_for :users
  resources :users do
         resources :messages do
           collection do
             post :delete_selected
           end
         end
       end
  resources :photos
  match "top" => "public_pages#top"
	# match "show" => "photos#show",:as => :photo
	root :to => "public_pages#home"
end

app/models/message.rb
class Message < ActiveRecord::Base

  is_private_message
  
  # The :to accessor is used by the scaffolding,
  # uncomment it if using it or you can remove it if not
  attr_accessor :to
  attr_accessible :recipient_id, :sender_id, :subject, :body
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  before_filter :set_user
  
  def index
    if params[:mailbox] == "sent"
      @messages = @user.sent_messages
    else
      @messages = @user.received_messages
    end
  end
  
  def show
    @message = Message.read_message(params[:id], @user)
  end
  
  def new
    @message = Message.new

    if params[:reply_to]
      @reply_to = @user.received_messages.find(params[:reply_to])
      unless @reply_to.nil?
        @message.to = @reply_to.recipient.username
        @message.subject = "Re: #{@reply_to.subject}"
        @message.body = "\n\n*Original message*\n\n #{@reply_to.body}"
      end
    end
  end
  
  def create
    @message = Message.new
    @message.subject = params[:message][:subject].to_s
    @message.body = params[:message][:body].to_s
    @message.sender = User.find_by_id(params[:message][:sender_id])
    @message.recipient = User.find_by_id(params[:message][:recipient_id])

    if @message.save
      flash[:notice] = "Message Sent"
      redirect_to user_messages_path(@user)
    else
      render :action => :new
    end
  end
  
  def delete_selected
    if request.post?
      if params[:delete]
        params[:delete].each { |id|
          @message = Message.find(:first, :conditions => ["messages.id = ? AND (sender_id = ? OR recipient_id = ?)", id, @user, @user])
          @message.mark_deleted(@user) unless @message.nil?
        }
        flash[:notice] = "Messages deleted"
      end
      redirect_to :back
    end
  end
  
  private
    def set_user
      @recipient = User.find_by_id(params[:user_id])
      @user = current_user
    end
end

app/views/messages/_inbox.html.erb
<h2>Inbox</h2>
<table>
	
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<tr>
			<th>Del?</th>
			<th>Sent</th>
			<th>Sender</th>
			<th>Sent</th>
		</tr>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td>
					<% if message.message_read? %>
					  <%= link_to h(message.subject), user_message_path(@user, message) %>
					<% else %>
					  <%= link_to "#{h(message.subject)} (unread)", user_message_path(@user, message) %>
					<% end %>
				</td>
				<td><%= link_to h(message.sender.email), user_path(message.sender) %></td>
		    <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
	<% end %>
</table>
<%= link_to "Sent", user_messages_path(@user, :mailbox => :sent)%>

app/views/messages/_sent.html.erb
<h2>Sent</h2>
<table>
	
	<% if @messages.size == 0 %>
		<tr>
			<td colspan="4">
				No messages
			</td>
		</tr>
	<% else %>
		<tr>
			<th>Del?</th>
			<th>Subject</th>
			<th>To</th>
			<th>Sent</th>
		</tr>
		<% for message in @messages %>
			<tr>
				<td><%= check_box_tag "delete[]", message.id %></td>
				<td><%= link_to h(message.subject), user_message_path(@user, message) %></td>
  			<td><%= link_to h(message.recipient.username), user_path(message.recipient) %></td>
			  <td><%=h message.created_at.to_s(:long) %></td>
			</tr>
		<% end %>
		<tr>
			<td colspan="4">
				<%= submit_tag "Delete" %>
			</td>
		</tr>
 	<% end %>
</table>
<%= link_to "Inbox", user_messages_path(@user)%>

app/views/messages/index.html.erb
<%= form_tag delete_selected_user_messages_path(@user, :method => :post) do %>
	<% if params[:mailbox] == "sent" %>
			<%= render :partial => "sent" %>
	<% else %>
			<%= render :partial => "inbox" %>
		<% end %>
<% end %>

app/views/messages/new.html.erb
<%= form_for @message, :url => user_messages_path(@user) do |f| %>
  <fieldset>
    <legend>Send Message</legend>
    <% if !@reply_to.nil? %>
        <%= f.hidden_field :recipient_id, :value => @reply_to.sender_id %>
        <%= f.hidden_field :sender_id, :value => @reply_to.recipient_id  %>
    <% else %>
        <%= f.hidden_field :recipient_id, :value => @recipient.id %>
        <%= f.hidden_field :sender_id, :value => @user.id %>
    <% end %>

    <%= f.label :subject %>
    <%= f.text_field :subject %>

    <%= f.label :message %>
    <%= f.text_area :body %>

    <%= submit_tag "Send", :class => "button" %>
    <section class="bottom-margin"></section>
  </fieldset>
<% end %>

app/views/messages/show.html.erb
<p>
  <strong>From:</strong> 
  <%= @message.sender == @user ? link_to("You", user_path(@user)) : link_to(h(@message.sender.email), user_path(@message.sender)) %>
</p>

<p>
  <strong>Received:</strong> 
  <%= @message.created_at.to_s(:long) %>
</p>

<p>
  <strong>To:</strong> 
  <%= @message.recipient == @user ? link_to("You", user_path(@user)) : link_to(h(@message.recipient.username), user_path(@message.recipient)) %>
</p>

<p>
  <strong>Message</strong><br />
  <%=h @message.body %>
</p>

<p>
  <% if @message.recipient == @user %>
	  <%= link_to "Reply", new_user_message_path(@user, :reply_to => @message) %> |
  <% end %>
  <%= link_to "Inbox", user_messages_path(@user)%>
</p>