config/routes.rb
Smartorhot::Application.routes.draw do
  resources :extended_profiles
  match 'vote_smart/:id' => 'extended_profiles#vote_smart'
  match 'vote_dumb/:id' => 'extended_profiles#vote_dumb'
  match 'vote_hot/:id' => 'extended_profiles#vote_hot'
  match 'vote_ugly/:id' => 'extended_profiles#vote_ugly'
  
  devise_for :users
  resources :users do
         resources :messages do
           collection do
             post :delete_selected
           end
         end
       end
  resources :photos
  match "top" => "public_pages#top"
	# match "show" => "photos#show",:as => :photo
	root :to => "public_pages#home"
end

app/models/extended_profile.rb
class ExtendedProfile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :date_of_birth, :user_id, :avatar, :first_name, :ispremium, :last_name, :phone_number, :references, :sex, :about
  has_attached_file :avatar, :storage => :dropbox, :dropbox_credentials => "#{Rails.root}/config/dropbox.yml", :styles => { :medium => "300x325#", :thumb => "100x100#" }, :dropbox_options => {:unique_filename => true,:path => proc { |style| "#{style}/#{id}_#{avatar.original_filename}"}}
  validates_attachment_presence :avatar
  validates :first_name, :length => {:in => 0..50}
  validates :last_name, :length => {:in => 0..50}
end

app/controllers/extended_profiles_controller.rb
class ExtendedProfilesController < ApplicationController
  
  # GET /extended_profiles
  # GET /extended_profiles.json
  def index
    @extended_profiles = ExtendedProfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @extended_profiles }
    end
  end

  # GET /extended_profiles/1
  # GET /extended_profiles/1.json
  def show
    @extended_profile = ExtendedProfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @extended_profile }
    end
  end

  # GET /extended_profiles/new
  # GET /extended_profiles/new.json
  def new
    @extended_profile = ExtendedProfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @extended_profile }
    end
  end

  # GET /extended_profiles/1/edit
  def edit
    @extended_profile = ExtendedProfile.find(params[:id])
  end

  # POST /extended_profiles
  # POST /extended_profiles.json
  def create
    @extended_profile = ExtendedProfile.new(params[:extended_profile])

    respond_to do |format|
      if @extended_profile.save
        format.html { redirect_to edit_user_registration_path, notice: 'Extended profile was successfully created.' }
        format.json { render json: @extended_profile, status: :created, location: @extended_profile }
      else
        format.html { redirect_to edit_user_registration_path }
        format.json { render json: @extended_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /extended_profiles/1
  # PUT /extended_profiles/1.json
  def update
    @extended_profile = ExtendedProfile.find(params[:id])

    respond_to do |format|
      if @extended_profile.update_attributes(params[:extended_profile])
        format.html { redirect_to edit_user_registration_path, notice: 'Extended profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to edit_user_registration_path, notice: 'Failed to update extended profile.' }
        format.json { render json: @extended_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extended_profiles/1
  # DELETE /extended_profiles/1.json
  def destroy
    @extended_profile = ExtendedProfile.find(params[:id])
    @extended_profile.destroy

    respond_to do |format|
      format.html { redirect_to extended_profiles_url }
      format.json { head :no_content }
    end
  end

  def vote_smart
    voting_relationship = UserVote.find_or_create_by_candidate_user_id_and_user_id(params[:id], current_user.id)
    if !voting_relationship.smart_vote? and !voting_relationship.dumb_vote?
      candidate = User.find_by_id(params[:id])

      if candidate
        voting_relationship.smart_vote = true
        voting_relationship.dumb_vote = true
        voting_relationship.save() 
        rating = Rating.find_or_create_by_user_id(candidate.id)
        Rating.increment_counter(:smart_count, rating)
        Rating.increment_counter(:total_positive_votes, rating)
        rating.save()
      else
        flash[:alert] = "User does not exist!"
      end
    else
      flash[:alert] = "You have already cast smartness vote!"
    end

    redirect_to (top_url)
  end

  def vote_dumb
    voting_relationship = UserVote.find_or_create_by_candidate_user_id_and_user_id(params[:id], current_user.id)
    if !voting_relationship.smart_vote? and !voting_relationship.dumb_vote?
      candidate = User.find_by_id(params[:id])

      if candidate 
        voting_relationship.dumb_vote = true
        voting_relationship.smart_vote = true
        voting_relationship.save()
        rating = Rating.find_or_create_by_user_id(candidate.id)
        Rating.increment_counter(:dumb_count, rating)
        rating.save()
      else
        flash[:alert] = "User does not exist!"
      end
    else
      flash[:alert] = "You have already cast smartness vote!"      
    end

    redirect_to (top_url)
  end

  def vote_hot
    voting_relationship = UserVote.find_or_create_by_candidate_user_id_and_user_id(params[:id], current_user.id)
    if !voting_relationship.hot_vote? and !voting_relationship.ugly_vote?
      candidate = User.find_by_id(params[:id])

      if candidate 
        voting_relationship.hot_vote = true
        voting_relationship.ugly_vote = true
        voting_relationship.save()
        rating = Rating.find_or_create_by_user_id(candidate.id)
        Rating.increment_counter(:hot_count, rating)
        Rating.increment_counter(:total_positive_votes, rating)
        rating.save()
      else
        flash[:alert] = "User does not exist!"
      end
    else
      flash[:alert] = "You have already cast hotness vote!"
    end

    redirect_to (top_url)
  end

  def vote_ugly
    voting_relationship = UserVote.find_or_create_by_candidate_user_id_and_user_id(params[:id], current_user.id)
    if !voting_relationship.hot_vote? and !voting_relationship.ugly_vote?
      candidate = User.find_by_id(params[:id])

      if candidate 
        voting_relationship.ugly_vote = true
        voting_relationship.hot_vote = true
        voting_relationship.save()
        rating = Rating.find_or_create_by_user_id(candidate.id)
        Rating.increment_counter(:ugly_count, rating)
        rating.save()
      else
        flash[:alert] = "User does not exist!"
      end
    else
      flash[:alert] = "You have already cast hotness vote!"
    end
    redirect_to (top_url)
  end

end

app/helpers/extended_profiles_helper.rb
module ExtendedProfilesHelper
end

app/views/extended_profiles/_form.html.erb
<%= form_for(@extended_profile) do |f| %>
  <% if @extended_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@extended_profile.errors.count, "error") %> prohibited this extended_profile from being saved:</h2>

      <ul>
      <% @extended_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :ispremium %><br />
    <%= f.check_box :ispremium %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.check_box :sex %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/extended_profiles/_show.html.erb
<%= image_tag @extended_profile.avatar.url(:medium) %>

app/views/extended_profiles/_user_photo.html.erb
<% if !(user.avatar.content_type =~ /^image/).nil? %>
  <div class="four columns photo" align=center>
    <%= link_to image_tag(user.avatar.url(:medium), :style => "width:300px;height:325px;"), user_path(user.user_id) %>
    <div class="panel">
      <table style="margin: 0;">
        <tr>
          <td>
            <table style="margin: 0;">
               <tr>
                <td rowspan=2>
                  <div id="<%=user.id %>simpleGraph"></div>
                </td>
                <td>
                  <% if current_user and user.user_id != current_user.id %>
                    <%= link_to "&#x25B2;".html_safe, {:controller => "extended_profiles", :action => "vote_smart", :id => user.user_id}, :title => "Vote Up" %>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td style="background-color: white">
                  <% if current_user and user.user_id != current_user.id %>
                    <%= link_to "&#x25BC;".html_safe, {:controller => "extended_profiles", :action => "vote_dumb", :id => user.user_id}, :title => "Vote Down" %>
                  <% end %>
                </td>
              </tr>
            </table>
            <script type="text/javascript">
                     ids.push(<%=user.id %>);
                     datas.push(new Array([[<%= smart_percent(user.user_id) %> , 100 - <%= smart_percent(user.user_id) %>],'Smartness']) );
                     votes.push(<%= Rating.find_or_create_by_user_id(user.user_id).smart_count%>);
            </script>
          </td>
          <td>
            <table style="margin: 0;">
              <tr>
                <td rowspan=2>
                  <div id="<%=user.id %>FsimpleGraph"></div>
                </td>
                <td>
                <% if current_user and user.user_id != current_user.id %>
                  <%= link_to "&#x25B2;".html_safe, {:controller => "extended_profiles", :action => "vote_hot", :id => user.user_id}, :title => "Vote Up" %>
                <% end %>
                </td>
              </tr>
              <tr>
                <td style="background-color: white">
                  <% if current_user and user.user_id != current_user.id %>
                  <%= link_to "&#x25BC;".html_safe, {:controller => "extended_profiles", :action => "vote_ugly", :id => user.user_id}, :title => "Vote Down" %>
                  <% end %>
                </td>
              </tr>
            </table>
              <script type="text/javascript">
                       ids.push(<%=user.id %> + 'F');
                       datas.push(new Array([[<%= hot_percent(user.user_id) %> , 100 - <%= hot_percent(user.user_id) %>],'Hotness']) );
                       votes.push(<%= Rating.find_or_create_by_user_id(user.user_id).hot_count %>);
              </script>
          </td>
        </tr>
      </table>
    </div>
  </div>
<% end %>

app/views/extended_profiles/edit.html.erb
<h1>Editing extended_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @extended_profile %> |
<%= link_to 'Back', extended_profiles_path %>

app/views/extended_profiles/index.html.erb
<h1>Listing extended_profiles</h1>

<table>
  <tr>
    <th>References</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Phone number</th>
    <th>Ispremium</th>
    <th>Date of birth</th>
    <th>Sex</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @extended_profiles.each do |extended_profile| %>
  <tr>
    <td><%= extended_profile.references %></td>
    <td><%= extended_profile.first_name %></td>
    <td><%= extended_profile.last_name %></td>
    <td><%= extended_profile.phone_number %></td>
    <td><%= extended_profile.ispremium %></td>
    <td><%= extended_profile.date_of_birth %></td>
    <td><%= extended_profile.sex %></td>
    <td><%= link_to 'Show', extended_profile %></td>
    <td><%= link_to 'Edit', edit_extended_profile_path(extended_profile) %></td>
    <td><%= link_to 'Destroy', extended_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Extended profile', new_extended_profile_path %>

app/views/extended_profiles/new.html.erb
<h1>New extended_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', extended_profiles_path %>

app/views/extended_profiles/show.html.erb
<p id="notice"><%= notice %></p>

 <%= image_tag @extended_profile.avatar.url %>

<p>
  <b>First name:</b>
  <%= @extended_profile.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @extended_profile.last_name %>
</p>

<p>
  <b>Phone number:</b>
  <%= @extended_profile.phone_number %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @extended_profile.date_of_birth %>
</p>

<p>
  <b>Sex:</b>
  <%= @extended_profile.sex %>
</p>


<%= link_to 'Edit', edit_extended_profile_path(@extended_profile) %> |
<%= link_to 'Back', extended_profiles_path %>