config/routes.rb
Smartorhot::Application.routes.draw do
  resources :extended_profiles
  match 'vote_smart/:id' => 'extended_profiles#vote_smart'
  match 'vote_dumb/:id' => 'extended_profiles#vote_dumb'
  match 'vote_hot/:id' => 'extended_profiles#vote_hot'
  match 'vote_ugly/:id' => 'extended_profiles#vote_ugly'
  
  devise_for :users
  resources :users do
         resources :messages do
           collection do
             post :delete_selected
           end
         end
       end
  resources :photos
  match "top" => "public_pages#top"
	# match "show" => "photos#show",:as => :photo
	root :to => "public_pages#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Smart or Hot" %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
  <script type="text/javascript">
  var ids = [];
  var datas = [];
  var votes = [];
  </script>
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- Basic Needs -->
  <div class="row">
  <div class="twelve columns">
    <nav class="top-bar">
       <ul>
        <!-- Title Area -->
        <li class="name">
          <%= link_to image_tag("soh.svg", :size => '44x44'), root_path(), :class => 'logo' %>
        </li>
        <li class="toggle-topbar"><a href="#"></a></li>
      </ul>

      <section>
        <!-- Left Nav Section -->
        <ul class="left">
          <li class="divider"></li>
          <% if user_signed_in? %>
          <%= nav_link 'Vote', root_path %>
          <% else %>
          <%= nav_link 'Home', root_path %>
          <% end %>
          <%= nav_link "Highest Rated", top_path() %>
          <li class="divider hide-for-small"></li>
        </ul>

        <!-- Right Nav Section -->
        <ul class="right">
          <li class="divider show-for-medium-and-up"></li>
          <% if user_signed_in? %>
          <% if current_user.unread_messages? %>
          <%= nav_link "Inbox(#{current_user.unread_message_count})", user_messages_path(current_user) %>
          <% else %>
          <%= nav_link 'Inbox', user_messages_path(current_user) %>
          <% end %>
          <li class="has-dropdown">
            <%= link_to 'My Account', user_path(current_user) %>
            <ul class="dropdown">
              <%= nav_link 'View', user_path(current_user) %>
              <%= nav_link 'Edit', edit_user_registration_path %>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
          <% else %>
          <%= nav_link 'Sign In', user_session_path %>
          <% end %>
        </ul>
      </section>
    </nav>
  </div>
</div>
  <article class="content">
    <% if notice %>
      <div class="alert-box success">
        <%= notice %>
        <a href="" class="close">&times;</a>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert-box alert">
        <%= alert %>
        <a href="" class="close">&times;</a>
      </div>
    <% end %>
    <%= yield %>
  </article>
</div>
</body>
</html>